
export const API_ENDPOINTS = {

  ATTACHMENTS: "attachments",
  ANALYTICS: "analytics",
  ATTRIBUTES: "attributes",
  ATTRIBUTE_VALUES: "attribute-values",
  ORDER_STATUS: "order_status",
  ORDERS: "orders",
  USERS: "users",
  REGISTER: "register",
  PRODUCTS: "products",
  PRODUCT_STATUS_UPDATE:"status-product",
  POPULAR_PRODUCTS: "popular-products",
  COUPONS: "coupons",
  CUSTOMERS: "customers",
  TAXES: "taxes",
  SHIPPINGS: "shipping",
  SETTINGS: "settings",
  CATEGORIES: "categories",
  SHOP_CATEGORIES: "shop-categories",

  SELECT_SHOP_CATEGORIES:"select-shop-categories",
  TAGS: "tags",
  PARENT_CATEGORIES: "fetch-parent-category",
  OFFER: "offers",
  FETCH_SHOP_CATEGORIES:"fetch-shop-category",
  TYPES: "types",
  PROFILE_UPDATE: "profile-update",
  LOGOUT: "logout",
  ME: "me",
  TOKEN: "token",
  BLOCK_USER: "users/ban-user",
  UNBLOCK_USER: "users/active-user",
  CHANGE_PASSWORD: "change-password",
  FORGET_PASSWORD: "forget-password",
  VERIFY_FORGET_PASSWORD_TOKEN: "verify-forget-password-token",
  RESET_PASSWORD: "reset-password",
  DOWNLOAD_INVOICE: "download/invoice",
  APPROVE_SHOP: "approve-shop",
  DISAPPROVE_SHOP: "disapprove-shop",
  SHOP_DELIVERY_STATUS: "shop-delivery-status",
  SHOPS: "all-shop",
  ADMIN_SHOP:"admin-shop",
  MY_SHOPS: "my-shops",
  WITHDRAWS: "withdraws",
  APPROVE_WITHDRAW: "approve-withdraw",
  APPROVE_INVOICE_UPLOAD: "approve-invoice-upload",
  STAFFS: "staffs",
  ADD_STAFF: "users/add-staff",
  MASTER_PRODUCT: "master-products",
  PRODUCT_OFFERS:"product-offers",
  PAGINATION_MASTER_PRODUCT: "pagination-master-products",
  STORE_MASTER_PRODUCT: "store-master-product",
  CREATED_MASTER_PRODUCT:"created-master-products",
  MASTER_PRODUCT_STATUS_UPDATE:"status-master-product",
  PRODUCT_COMMISSSION:"products-commission",
  SHOP_COMMISSION:"shop-commission",
  SHOP_COMMISSION_TYPE:"shop-commission-type",
  UPDATE_REFERRAL_COMMISSION:"update-referral-commission",
  GET_REFERRAL_COMMISSION:"get-referral-commission",
  USER_VERIFY:"user-verify",
  RESEND_CODE:"resend-code",
  IMPORT_PRODUCTS: "import-products/",
  IMPORT_ALL_PRODUCTS: "import-all-products/",
  IMPORT_ATTRIBUTES: "import-attributes/",
  IMPORT_VARIATION_OPTIONS: "import-variation-options/",
  IMPORT_ALL_VARIATION_OPTIONS: "import-all-variation-options/",
  IMPORT_MASTER_VARIATION_OPTIONS: "import-master-variation-options/",
  IMPORT_MASTER_PRODUCTS: "import-master-products/",
  IMPORT_SHOPS: "import-shops/",
  LOGS:"logs",
  SIGNUP_OFFER: "signup-offer",
  STORE_LICENSES:"stored-licenses",
  STORE_LICENSE_ATTACHMENT:"store-license-attachment",
  ALL_TAXES:"all-taxes",
  INVOICES_REWARD: 'invoices-reward',
  BILL: 'bill',
  BILL_REWARD: 'bill-reward',
  APPROVE_BILL: "approve-bill",
  ADMIN_DELIVERY:'admin/delivery',
  DELIVERY:'delivery',
  APPROVE_DELIVERY: "approve-delivery",
  SHOP_DELIVERY_CONFIG: "shop-delivery-config",
  DELIVERY_COST:"delivery-cost",
  VERIFY_CHECKOUT: "checkout/verify",

  CONTACT: '/contact',

  GET_WALLET_COMMISSION:"get-wallet-commission",
  GET_USER_WALLET_DETAILS:"get-user-wallet-details",

};

