
export const API_ENDPOINTS: Record<string, string> = {
  
  PRODUCTS: "products",
  SETTINGS: "settings",
  CUSTOMER: "me",
  COUPONS: "coupons",
  CATEGORY: "categories",
  PARENT_CATEGORIES: "fetch-parent-category",
  TYPE: "types",
  UPLOAD: "attachments",
  ORDER: "orders",
  ORDER_STATUS: "order_status",
  LOGIN: "token",
  SOCIAL_LOGIN: "social-login-token",
  REGISTER: "register",
  FORGET_PASSWORD: "forget-password",
  LOGOUT: "logout",
  CHANGE_PASSWORD: "change-password",
  RESET_PASSWORD: "reset-password",
  VERIFY_FORGET_PASSWORD: "verify-forget-password-token",
  VERIFY_CHECKOUT: "checkout/verify",
  CONTACT: "contact",
  ADDRESS: "address",
  SHOPS: "all-shop",
  HOME_FEATURE_SHOPS:"fetch-feature-shops",
  HOME_FEATURE_STORES:"fetch-feature-stores",
  HOME_FEATURE_PRODUCTS:"fetch-feature-products",
  HOME_OFFERS:"fetch-offers",
  HOME_CATEGORIES:"fetch-home-categories",
  SEARCH:"search",
  REFERRAL_NETWORK:"referral-network",
  GET_WALLET_COMMISSION:"get-wallet-commission",
  USER_VERIFY:"user-verify",
  RESEND_CODE:"resend-code"
};
