export const ROUTES = {
  DASHBOARD: "/",
  SHOPS: "/shops",
  ADMIN_MY_SHOPS: "/my-shops",
  CREATE_SHOP: "/shops/create",
  LOGIN: "/login",
  ORDER_STATUS: "/order-status",
  ORDERS: "/orders",
  DELIVERY: '/delivery',
  DELIVERY_COST: '/delivery-cost',
  PRODUCTS: "/products",
  COUPONS: "/coupons",
  USERS: "/users",
  TAXES: "/taxes",
  SHIPPINGS: "/shippings",
  SETTINGS: "/settings",
  STORE_SETTINGS: "/vendor/settings",
  STORE_KEEPER: "/vendor/store_keepers",
  CATEGORIES: "/categories",
  SHOP_CATEGORIES: "/shop-categories",
  OFFERS:"/offers",
  ATTRIBUTES: "/attributes",
  ATTRIBUTE_VALUES: "/attribute-values",
  GROUPS: "/groups",
  TAGS: "/tags",
  WITHDRAWS: "/withdraws",
  PROFILE_UPDATE: "/profile-update",
  LOGOUT: "/logout",
  STAFFS: "/staffs",
  MASTER_PRODUCT:"/master-products",
  COMMISSION:"/commission",
  LOGS:'/logs',
  SIGNUP_OFFERS:"/signup-offers",
  INVOICES_REWARD: '/invoices-reward',
  INVOICES_REWARD_DATA: '/invoices-reward-data',
};
